esphome:
  name: led_blink
  platform: ESP8266
  board: esp01_1m

# Твои настройки Wi-Fi
wifi:
  ssid: "TP-LINK842"
  password: "an9968vo"

# Включаем API для связи с Home Assistant
api:
  password: "an9968vo"

# Логгер для отладки (выводит данные в консоль)
logger:

# Добавляем кнопки в интерфейс Home Assistant
switch:
  - platform: gpio
    pin: GPIO0
    name: "ESP01 LED Blue (GPIO0)"
  - platform: gpio
    pin: GPIO2
    name: "ESP01 LED External (GPIO2)"
